// splash actions
export const SPLASH_TIMEOUT_ACTION_START = 'SPLASH_TIMEOUT_ACTION_START';
export const SPLASH_TIMEOUT_ACTION_FINISHED = 'SPLASH_TIMEOUT_ACTION_FINISHED';
export const SPLASH_TIMEOUT_ACTION_CANCEL = 'SPLASH_TIMEOUT_ACTION_CANCEL';

