// splash actions
export const SPLASH_TIMEOUT_ACTION_START = 'SPLASH_TIMEOUT_ACTION_START';
export const SPLASH_TIMEOUT_ACTION_FINISHED = 'SPLASH_TIMEOUT_ACTION_FINISHED';
export const SPLASH_TIMEOUT_ACTION_CANCEL = 'SPLASH_TIMEOUT_ACTION_CANCEL';

// login actions
export const LOGIN_ACTION_PERFORM = 'LOGIN_ACTION_PERFORM';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_ERROR = 'LOGIN_ACTION_ERROR';
export const LOGIN_ACTION_ERROR_CLEAR = 'LOGIN_ACTION_ERROR_CLEAR';
export const LOGIN_ACTION_CANCEL = 'LOGIN_ACTION_CANCEL';

// registration actions
export const REGISTRATION_ACTION_PERFORM = 'REGISTRATION_ACTION_PERFORM';
export const REGISTRATION_ACTION_SUCCESS = 'REGISTRATION_ACTION_SUCCESS';
export const REGISTRATION_ACTION_ERROR = 'REGISTRATION_ACTION_ERROR';
export const REGISTRATION_ACTION_ERROR_CLEAR = 'REGISTRATION_ACTION_ERROR_CLEAR';
export const REGISTRATION_ACTION_CANCEL = 'REGISTRATION_ACTION_CANCEL';
export const REGISTRATION_ACTION_CANCELLED = 'REGISTRATION_ACTION_CANCELLED';

// profile
export const USER_LOG_OUT_ACTION = 'USER_LOG_OUT_ACTION';
export const USER_LOG_OUT_ACTION_SUCCESS = 'USER_LOG_OUT_ACTION_SUCCESS';
export const USER_LOG_OUT_ACTION_ERROR = 'USER_LOG_OUT_ACTION_ERROR';
export const USER_LOG_OUT_ERROR_CLEAR = 'USER_LOG_OUT_ERROR_CLEAR';
export const USER_GET_DETAILS_ACTION = 'USER_GET_DETAILS_ACTION';
export const USER_GET_DETAILS_ACTION_SUCCESS = 'USER_GET_DETAILS_ACTION_SUCCESS';
export const USER_GET_DETAILS_ACTION_ERROR = 'USER_GET_DETAILS_ACTION_ERROR';
export const APP_LANGUAGE_SET_ACTION = 'APP_LANGUAGE_SET_ACTION';
export const USER_CLEAR_DATA = 'USER_CLEAR_DATA';
export const USER_SAVE = 'USER_SAVE';
// update names
export const USER_UPDATE_NAMES = 'USER_UPDATE_NAMES';
export const USER_UPDATE_NAMES_SUCCESS = 'USER_UPDATE_NAMES_SUCCESS';
export const USER_UPDATE_NAMES_ERROR = 'USER_UPDATE_NAMES_ERROR';
// change password
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_ERROR = 'USER_CHANGE_PASSWORD_ERROR';

//favourites
export const FAVOURITES_ADD_TO_LIST = 'FAVOURITES_ADD_TO_LIST';
export const FAVOURITES_REMOVE_FROM_LIST = 'FAVOURITES_REMOVE_FROM_LIST';
export const FAVOURITES_CLEAR_LIST = 'FAVOURITES_CLEAR_LIST';

//categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const GET_CATEGORIES_CANCEL = 'GET_CATEGORIES_CANCEL';
export const GET_CATEGORIES_CANCELLED = 'GET_CATEGORIES_CANCELLED';

//cart
export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_ERROR = 'GET_CART_ERROR';
export const GET_CART_CANCEL = 'GET_CART_CANCEL';
export const GET_CART_CANCELLED = 'GET_CART_CANCELLED';

//my orders
export const GET_MY_ORDERS = 'GET_MY_ORDERS';
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const GET_MY_ORDERS_ERROR = 'GET_MY_ORDERS_ERROR';
export const GET_MY_ORDERS_CANCEL = 'GET_MY_ORDERS_CANCEL';
export const GET_MY_ORDERS_CANCELLED = 'GET_MY_ORDERS_CANCELLED';

//home search
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR';
export const SEARCH_PRODUCT_CANCEL = 'SEARCH_PRODUCT_CANCEL';
export const SEARCH_PRODUCT_CANCELLED = 'SEARCH_PRODUCT_CANCELLED';
export const SEARCH_LIST_CLEAR = 'SEARCH_LIST_CLEAR';

//home products
export const GET_HOME_PRODUCTS = 'GET_HOME_PRODUCTS';
export const GET_HOME_PRODUCTS_SUCCESS = 'GET_HOME_PRODUCTS_SUCCESS';
export const GET_HOME_PRODUCTS_ERROR = 'GET_HOME_PRODUCTS_ERROR';
export const GET_HOME_PRODUCTS_CANCEL = 'GET_HOME_PRODUCTS_CANCEL';
export const GET_HOME_PRODUCTS_CANCELLED = 'GET_HOME_PRODUCTS_CANCELLED';

//product details
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_ERROR = 'GET_PRODUCT_DETAILS_ERROR';
export const GET_PRODUCT_DETAILS_CANCEL = 'GET_PRODUCT_DETAILS_CANCEL';
export const GET_PRODUCT_DETAILS_CANCELLED = 'GET_PRODUCT_DETAILS_CANCELLED';

//add product to cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_ERROR = 'ADD_PRODUCT_TO_CART_ERROR';
export const ADD_PRODUCT_TO_CART_CANCEL = 'ADD_PRODUCT_TO_CART_CANCEL';
export const ADD_PRODUCT_TO_CART_CANCELLED = 'ADD_PRODUCT_TO_CART_CANCELLED';


