// splash actions
export const SPLASH_TIMEOUT_ACTION_START = 'SPLASH_TIMEOUT_ACTION_START';
export const SPLASH_TIMEOUT_ACTION_FINISHED = 'SPLASH_TIMEOUT_ACTION_FINISHED';
export const SPLASH_TIMEOUT_ACTION_CANCEL = 'SPLASH_TIMEOUT_ACTION_CANCEL';

// login actions
export const LOGIN_ACTION_PERFORM = 'LOGIN_ACTION_PERFORM';
export const LOGIN_ACTION_SUCCESS = 'LOGIN_ACTION_SUCCESS';
export const LOGIN_ACTION_ERROR = 'LOGIN_ACTION_ERROR';
export const LOGIN_ACTION_CANCEL = 'LOGIN_ACTION_CANCEL';

// registration actions
export const REGISTRATION_ACTION_PERFORM = 'REGISTRATION_ACTION_PERFORM';
export const REGISTRATION_ACTION_SUCCESS = 'REGISTRATION_ACTION_SUCCESS';
export const REGISTRATION_ACTION_ERROR = 'REGISTRATION_ACTION_ERROR';
export const REGISTRATION_ACTION_CANCEL = 'REGISTRATION_ACTION_CANCEL';

// profile
export const USER_LOG_OUT_ACTION = 'USER_LOG_OUT_ACTION';
export const USER_LOG_OUT_ACTION_SUCCESS = 'USER_LOG_OUT_ACTION_SUCCESS';
export const USER_LOG_OUT_ACTION_ERROR = 'USER_LOG_OUT_ACTION_ERROR';
export const USER_LOG_IN_ACTION_SUCCESS = 'USER_LOG_IN_ACTION_SUCCESS';
export const USER_GET_DETAILS_ACTION = 'USER_GET_DETAILS_ACTION';
export const USER_GET_DETAILS_ACTION_SUCCESS = 'USER_GET_DETAILS_ACTION_SUCCESS';
export const USER_GET_DETAILS_ACTION_ERROR = 'USER_GET_DETAILS_ACTION_ERROR';
export const APP_LANGUAGE_SET_ACTION = 'APP_LANGUAGE_SET_ACTION';
export const USER_UPDATE_NAMES = 'USER_UPDATE_NAMES';
export const USER_UPDATE_NAMES_SUCCESS = 'USER_UPDATE_NAMES_SUCCESS';
export const USER_UPDATE_NAMES_ERROR = 'USER_UPDATE_NAMES_ERROR';

//favourites
export const FAVOURITES_ADD_TO_LIST = 'FAVOURITES_ADD_TO_LIST';
export const FAVOURITES_REMOVE_FROM_LIST = 'FAVOURITES_REMOVE_FROM_LIST';

//categories
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const GET_CATEGORIES_CANCEL = 'GET_CATEGORIES_CANCEL';
export const GET_CATEGORIES_CANCELLED = 'GET_CATEGORIES_CANCELLED';

//cart
export const GET_CART = 'GET_CART';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_ERROR = 'GET_CART_ERROR';
export const GET_CART_CANCEL = 'GET_CART_CANCEL';
export const GET_CART_CANCELLED = 'GET_CART_CANCELLED';

//my orders
export const GET_MY_ORDERS = 'GET_MY_ORDERS';
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS';
export const GET_MY_ORDERS_ERROR = 'GET_MY_ORDERS_ERROR';
export const GET_MY_ORDERS_CANCEL = 'GET_MY_ORDERS_CANCEL';
export const GET_MY_ORDERS_CANCELLED = 'GET_MY_ORDERS_CANCELLED';

//home
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR';
export const SEARCH_PRODUCT_CANCEL = 'SEARCH_PRODUCT_CANCEL';
export const SEARCH_PRODUCT_CANCELLED = 'SEARCH_PRODUCT_CANCELLED';


