import LocalizedStrings from 'react-native-localization';

const strings = new LocalizedStrings({
  ru: {
    app_name: 'Amazon',
    log_in: 'Войти',
    or: 'Или',
    no_account: 'Нет аккаунта?',
    sign_up: 'Зарегистрироваться',
    registration: 'Регистрация',
    phone: 'Телефон',
    password: 'Пароль',
    name: 'Имя',
    lastName: 'Фамилия',
    email: 'E-mail',
    order_checkout: 'Оформление заказа',
    add_delivery_address: 'Добавить адрес доставки',
    payment_method_choose: 'Выберите способ оплаты',
    your_order: 'Ваш заказ',
    orders: 'Заказы',
    delivery: 'Доставка',
    order_details: 'Информация о доставке',
    contact_info: 'Контактные данные',
    delivery_address: 'Адрес доставки',
    save: 'Сохранить',
    search: 'Поиск',
    all_categories: 'Все категории',
    catalog: 'Каталог',
    what_to_find: 'Что вам найти?',
    popularSearches: 'Популярные запросы',
    bucket: 'Корзина',
    profile: 'Профиль',
    my_coupons: 'Мои купоны',
    favorites: 'Избранное',
    notifications: 'Уведомления',
    client_support: 'Поддержка клиентов',
    app_language: 'Язык приложения',
    profile_settings: 'Настройки профиля',
    personalData: 'Личные данные',
    change_password: 'Сменить пароль',
    log_out: 'Выйти',
  },
});

export default strings;
